title: Hoofbeats Health
title-short: hoofbeats
email: hoofbeats@domain.com
description: Understanding your healthcare and technology the evidenced-based way.
site-tagline: MedEd for the masses
site-quote: "When you hear Hoofbeats, think Horses, not Zebras."
baseurl: ""
url: "https://hoofbeats.github.io"
twitter_username: HoofbeatsHealth
github_username:  hoofbeats

# assets
favicon: /assets/images/favicon.ico

# build settings
collections:
  - graphics

excerpt_separator:  <!-- excerpt -->
permalink:  pretty
show_drafts:  false
markdown:  kramdown
kramdown:
  parse_block_html:  true
  input:  GFM

sass:
  sass_dir:  _sass
  style:  compressed

gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - LICENSE
  - package.json
  - README.md
  - Gemfile
  - gulpfile.babel.js
  - .babelrc
  - .gitignore
  - sass
  - _sass
  - scss
  - validate
  - CNAME
  - Gemfile.lock
  - google*.html
  - bower.json
  - bundle
  - src
  - script
  - scss
  - media
  - ".bundle"
  - vendor
  - bower_components
  - _drafts
  - references
  - dev
